# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'DevOps SPN - Excellus.com'
    backendAzureRmResourceGroupName: 'cloud-shell-storage-eastus'
    backendAzureRmStorageAccountName: 'cs2100320025a643c18'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'test.state'
    
 

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/LAB'
    backendServiceArm: 'DevOps SPN - Excellus.com'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DevOps SPN - Excellus.com'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list --output table'