# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'DevOps SPN - Excellus.com'
    backendAzureRmResourceGroupName: 'cloud-shell-storage-eastus'
    backendAzureRmStorageAccountName: 'cs2100320025a643c18'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'test.state'
    
 

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/LAB'
    backendServiceArm: 'DevOps SPN - Excellus.com'


